import { Nav } from "@/components/Nav";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="flex min-h-screen flex-col items-center justify-between p-4">
          <div className="w-full max-w-7xl items-center justify-between font-mono text-sm">
            <Nav />
            <article className="grid grid-flow-row sm:grid-cols-2 md:grid-cols-2 lg:grid-cols-3 relative gap-4">
              {children}
            </article>
          </div>
        </main>
      </body>
    </html>
  );
}
